### PR TITLE
Robot Validator Improvements

### PR DESCRIPTION
**Pull request by wilbertliu**
Hey all @dberget @markerikson,

Sorry for delaying this too long, but here we go. 🙂

So I managed to improve the parser and make it more verbose. But here are few things to note :

- It's not rigorously tested, so some bugs are expected.
- It's based on the markdown structure that discussed at #10.
- If you find something that you want to improve, feel free to jump in!

### CODE REVIEW

**Comment by markerikson** [comment]
Cool!  I'm hoping to spend time next week doing "maintainer-ish" stuff, which includes swinging back around and looking at things like this.

So FYI, Ilya Gelman told me he'd previously purchased the `redux-ecosystem.com` domain name, and would be happy to transfer it to me.  Haven't gone any further with that yet, but we should be able to figure out something to do with it :)

**Comment by nmay231** [comment]
Hey @wilbertliu @markerikson Do you want to try to bring this back to life? I was going to try to look at it, but I don't have the `database.json`file.

**Comment by markerikson** [comment]
Sure, it'd be neat if someone wanted to try tackling it again.

**Comment by nmay231** [comment]
Hey @wilbertliu, do you have any desire to work on this at all?

If not, I'll probably fork it and try to work on the problems with the robot parser.

**Comment by wilbertliu** [comment]
Unfortunately there's too much on my plate right now, @nmay231.

Go for it, I'd say.. 🙂

**Pull request closed without merging**
