### PR TITLE
[WIP] Card Based UI Mockup

### PR DESCRIPTION
**Pull request by dberget**
Here is a card based layout for the topics page, for issue #2. The main categories page is still "under construction", as well as most of it...

I've added express because i'm using https://github.com/dberget/reduxtionary for loading up some live data for the time being, we can remove before merging.

### CODE REVIEW

**Comment by wilbertliu** [comment]
Hello @dberget,
Thank you so much for making it! 🙂

Anyway, do you use [Prettier](https://github.com/prettier/prettier)? I found there are inconsistencies on the source code, like some of codes use semicolon, and some don't. I prefer to have one style of code, so we don't need to debate something like this. 😀

I will leave it as is for now, since it might be changing soon after we have discussed #1 and #2 as well.

Last but not least, I really appreciate our progress so far.
You're awesome man! 👍🏻🙌🏻

**Comment by dberget** [comment]
Hey @wilbertliu,  I agreed on the code consistency need, I'll get Prettier set up!

**Comment by wilbertliu** [comment]
Hello @dberget 👋🏻😀,

How's the progress so far? Just checking.., whether you need some thoughts or something. Is the **Current Screenshot** above is the latest one? I don't see any category / subcategory dropdown, but would love to know your reasons behind it. 🙂

**Comment by dberget** [comment]
Hey @wilbertliu, 

I think I mistook one of your comments to only include the filters and thought you meant to also remove the category dropdowns. Looking back on it now I don't really see that anywhere, i must have been tired or something... :) No big deal though, easy to reincorporate.

**Comment by wilbertliu** [comment]
Haha, alright, that's totally understandable. 😀
Just let me know when it's ready to test or review.

Also, I think I've mentioned you that I'm done with #5.
If you have any thoughts, I'm more than welcome. But if not, then I will merge it soon, so you could use the JSON here.

Cheers! 🙃

**Comment by dberget** [comment]
Sounds great, #5 looks 👍  to me. The generated JSON is very similar to what i was designing with so it will be very simple to switch over once you merge! Lets review/test after that has been done.

**Comment by dberget** [comment]
Hey @wilbertliu & @markerikson,
Here is a current screenshot for the category pages, I'd appreciate feedback from you guys on the the look. Couple of notes: 

The second dropdown only renders after the user selects a category in the top dropdown, it might be a little to restricting if they don't know what main category their trying to look in. So open to changing that for sure. 
I also thought it would be convenient to have the current categories topics listed for easy navigation, let me know what you think about that as well. 

image

**Comment by wilbertliu** [comment]
Hey @dberget 👋🏻,

I've put comments on #2 for deeper thoughts about this design direction (since you asked there as well). I just want to add few things based on your update here.

1. Why doesn't the grey box in the middle fill the rest of the _right-white_ section? I think we've discussed about that as well on #2.
2. The search looks like a lonely thing at the top right. Think about hiding that for now? Since we're still not sure on the performance of performing search as well.
3. I assume **USE CASES** is category, and **Assorted Use Cases** is subcategory, I think we should ditch them all to avoid unnecessary duplicate information. These informations should be visible on the left panel. Thus, we could use the whole grey box to display the boxes of repository.

Let me know what you think! 😀🙏🏻

**Comment by dberget** [comment]
Hey @wilbertliu,

> Why doesn't the grey box in the middle fill the rest of the right-white section? I think we've discussed about that as well on #2.

I keep meaning to bump it out and get distracted by something else! 😄 

> I assume USE CASES is category, and Assorted Use Cases is subcategory, I think we should ditch them all to avoid unnecessary duplicate information. These informations should be visible on the left panel. Thus, we could use the whole grey box to display the boxes of repository.

Yeah, correct. So just to get on the same page, currently when a user clicks a category they're being taken to a page with all the subcategories and its links for the given category, is that what we want or do we want each subcat to be its own page? I've added an image below of farther down the list to show you the current setup.  

I do agree there is duplication going on with the category & subcategory at the top, something should be changed on it, but I think if we're having all subcats on the same page the subcategory headers provide a nice division of information. 

image

**Comment by wilbertliu** [comment]
Ah, the last screenshot makes it clearer than before @dberget. That's a good idea I think! 👏🏻

Also, by implementing the new pattern that we've discussed on #2, I think we should highlight the category / subcategory on the left panel when people scroll and reach the respective category / subcategory, so the people wouldn't miss information about "Where am I right now". Do you get what I mean?

Just note that all of these things should be done on a single page. I don't think we need more than 1 page for now. 🤔

Alright, that's all. Maybe @markerikson wants to add something?

**Comment by dberget** [comment]
@wilbertliu 👋 , I've begun implementing the new menu design, and my concern is that due to the sheer amount of categories it is a bit hard to display them appropriately. Here is an "early access" screenshot, let me know your thoughts: 

image

**Comment by wilbertliu** [comment]
Hey @dberget, that’s a good starting approach. 🙂

Here are some thoughts :

- I think you should add a title `Categories :` above the list to make it clearer.
- The list of categories should be scrollable, so it could fit in one screen when we put the `Sort By :` below it.
- Perhaps you want to use bullets style for the name of categories? It’s also good to show the number of subcategories at the right of the category name. For example : `• Actions (20)`.
- The category name should be title-case I think?
- I think the indentation of subcategories is too deep. Better to move them few pixels to the left.
- Also, you might want to use bullets for subcategories but with different style because of its indentation?
- I think we should provide an `All` option as the first item of subcategory, since people could also have a willing to see all subcategories at once.

Let me know if it’s not clear or something.
Cheers.. 😊🙏🏻

**Comment by dberget** [comment]
Hey @wilbertliu, sorry i've slowed down on this over the last couple weeks, work picked up again.

While its still rough in spots, I think the PR is in a decent place for a review and then if possible, merging. I think it gives the UI a decent starting point that people can make improvements on, etc. Sorry, I probably got a little carried away doing it all out in one PR like this... 

I can open up some issues to cover some of the features or designs changes we've discussed that haven't been implemented or that I know are weaknesses in my PR. 

The main next improvements we'll want to make are: 
1. - [ ] Design improvements to the index page and side menu.
2. - [ ] Add sorting functionality.

Let me know, thanks! 😄

**Comment by markerikson** [comment]
I'm afraid I haven't had any time to look through what's happening with this repo, but I love that you two have jumped on the idea and are running with it :)  I may have a bit of time to glance at it this next weekend.  Keep on going! :)

**Comment by dberget** [comment]
Sounds good @markerikson, there really hasn't been too many changes since you last popped in. We merged #3, but then Its been mostly me tinkering with the UI in this PR. We do have a relatively functional MVP at this point though, so it should get us off the ground. Looking forward to any feedback you may have! :)

**Comment by wilbertliu** [comment]
Hey @dberget,

Sorry for taking this so long. I've reviewed roughly about what you're doing, it's awesome! 😀
Will merge this to master then!

And feel free to add new issues or something, but I personally will wait for @markerikson to
decide what he would do regarding the markdown structure, then resume the work after it has some clarity. Note that I can't run `node robot/index.js` anymore due to an error that caused by some markdown. Therefore, I had to inject my old `database.json` to review this PR properly.

Again Dave, thank you for a great work! 🙏🏻

**Comment by dberget** [comment]
@wilbertliu Awesome, was fun to work on! :) 

Yeah, a couple of times the robot would fail for me too, but then it would work trying a second time.

**Pull request merged**
