### PR TITLE
[WIP] The Robot

### PR DESCRIPTION
**Pull request by wilbertliu**
Hello everyone 👋🏻,
Based on issue #3, I will work through this PR until done.

Feel free to give some feedbacks whatsoever.
Thank you! 😀🙏🏻

### CODE REVIEW

**Comment by markerikson** [comment]
Worth noting that the layout format isn't always 100% consistent.  For example:

- sometimes there are multiple Github links for one lib header
- For a few libraries, I've also included a link to a blog post that announced the library or similar
- There's a few Github Gist links in there
- There may be a couple libs that point to NPM package pages instead of Github repos
- Some of the categories have some links to "Related Topics" before the list itself starts

Also, per the original ["highlight top libraries" issue](https://github.com/markerikson/redux-ecosystem-links/issues/60), one of these days I may get around to adding some kind of emoji or something to libs I particularly recommend.  Would be neat if the parsing could pick that up.  (But, since I haven't started doing that yet, that can also come later.)

**Comment by markerikson** [comment]
Also, every so often I do some refactoring and rearranging of categories.  So, it might be simplest if the parsing process just completely rebuilds the list and indexing from scratch every time

**Comment by wilbertliu** [comment]
Hello @markerikson 👋🏻,

Yes, I've noticed that when building it – some of the repos are not parsed correctly because some of facts that you've mentioned above. Being that said, isn't it good to have a consistent layout format? Because then the data could be parsed correctly without having to change the parser in future. My initial plan is to fork your repo and fix few links from there, and run the robot to parse from the forked repo instead. But of course it will be better if you want those fixed changes to be merged on your repo by a PR. What's your take on this? 😀

> Also, per the original "highlight top libraries" issue, one of these days I may get around to adding some kind of emoji or something to libs I particularly recommend. Would be neat if the parsing could pick that up. (But, since I haven't started doing that yet, that can also come later.)

I'm not sure on where do you want to put the emoji. But in case you put that on the name of subcategory or even the name of repo, that should be parsed as well. 🙂

> Also, every so often I do some refactoring and rearranging of categories. So, it might be simplest if the parsing process just completely rebuilds the list and indexing from scratch every time

Yes. What's done so far is rebuilding the JSON file every time the robot runs, then replacing the existing JSON file that's used by the front-end if any – If not, the robot creates a new JSON. And no indexing whatsoever yet, see #1 because we're still discussing it. 👀😁

Let me know if you have any thoughts.
Thank you Mark! 🙏🏻

**Comment by markerikson** [comment]
Tell you what - see if you can come up with a list of where the list deviates from the normal pattern , and we can figure out how to handle things.

**Comment by wilbertliu** [comment]
For sure @markerikson! ~~But I think I will make an issue for that, so we can discuss in more focused way.~~ Alright, I will not make it complicated for now, so let's discuss it here. Please see my next comment below for this part.

Now the robot should be finished, do you want to do some code review whatsoever before I merge it to the master @markerikson @dberget? 🙂 It takes around 5 minutes to finish on my machine, and the bottleneck is on getting the metadata of GitHub repo and NPM – i.e I have to give timeouts, so the API server will not treat the robot as an abuser.

And here's the first few lines of the JSON that will be consumed by the front-end :
carbon

Let me know what you think! 🙏🏻

**Comment by wilbertliu** [comment]
Hey @markerikson 👋🏻,

Recently I added category content validator as a part of this work, because we want to know whether the markdown file that will be parsed is valid according to the parser.

The normal pattern that the parser expects is :

- Only one `<h3></h3>` allowed for every markdown file – since it's the name of category, and 1 markdown file means 1 category.
- For every `<h4></h4>`, it should be followed by the list of repository.
- For every repository, here's the valid structure in chronological order :
  - A paragraph (perhaps made by tabs?).
  - Bold title string.
  - Linebreak.
  - Valid GitHub repo URL string.
  - Linebreak.
  - Description string.

Note that the parser doesn't guarantee anything more or less than the above pattern. If you want, you could run it on your machine like this : `node robot/category-content-validator.js`. I've run that on mine, and here's the output `category-content-error.md` just in case you want to see 🙂 :

**action-reducer-generators.md**
- Repository Fredux of subcategory Boilerplate Reduction and Simplification has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**actions.md**
- Repository to-redux-type of subcategory Action Creation Utilities has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**apps-and-examples.md**
- Repository Redux Saga Examples of subcategory Purpose-Built Demos and Examples has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository Redux Counter Example of subcategory Purpose-Built Demos and Examples has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository Firefox DevTools - Memory Tool and Debugger of subcategory Applications has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository CarteJaune of subcategory Applications has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository Linode Manager of subcategory Applications has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository Winamp2-js of subcategory Applications has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository "Ask HN: Open source projects written in React?" of subcategory Other Application Lists has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository React Apps and Libraries List of subcategory Other Application Lists has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository Twitter: mobile.twitter.com of subcategory Redux Usage Stories has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository Lystable: Real World Redux of subcategory Redux Usage Stories has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository KarmaCRM: Launching an Enterprise React & Redux App – Part 1 of subcategory Redux Usage Stories has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository WaveHQ of subcategory Redux Usage Stories has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository Neos CMS Goes for a Full UI Rewrite with React and Redux of subcategory Redux Usage Stories has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository Reddit frontend engineering team AMA of subcategory Redux Usage Stories has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository Redux for Realtime Gaming of subcategory Redux Usage Stories has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**component-state.md**
- Repository Redux "subapps" example of subcategory Component/Local State has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-container-state of subcategory Component/Local State has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-internal-state of subcategory Component/Local State has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-doghouse of subcategory Component/Local State has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-atom of subcategory Component/Local State has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-features of subcategory Modularity and Encapsulation has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-modules-enhancer of subcategory Modularity and Encapsulation has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**devtools.md**
- Repository reselect-tools of subcategory DevTools has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository purityWarningReduxConnect of subcategory Mutation Detection has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository mutation-sentinel of subcategory Mutation Detection has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- `<h4>` is not followed by repositories.
- Repository react-transform-render-visualizer of subcategory Component Update Monitoring has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository "WhyDidYouUpdateMixin" of subcategory Component Update Monitoring has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository react-wastage-monitor of subcategory Component Update Monitoring has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**immutable-data.md**
- Repository Immutable.js of subcategory Immutable Data Structures (Specialized) has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository immutability-helper of subcategory Immutable Update Utilities has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository blazing-edge/update of subcategory Immutable Update Utilities has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-tcomb-actions of subcategory Immutable/Redux Interop has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository reduxdb of subcategory Alternate Data Management Concepts has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**library-integration.md**
- Repository number 1 of subcategory React has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**middleware-async.md**
- Repository redux-awaiter of subcategory Promises has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-queue-offline of subcategory Timeouts and Delays has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**middleware-network-requests.md**
- `<h3>` appears more than once.

**middleware-sockets-adapters.md**
- Repository redux-socket.io-connect of subcategory Websockets has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**middleware.md**
- Repository redux-aop of subcategory Action Grouping and Interception has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**other-resources.md**
- Repository Redux Docs: Ecosystem of subcategory Redux Links has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository Reactiflux of subcategory Redux Links has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository Black Pixel Redux Handbook of subcategory Community-Defined Standards has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**reducers.md**
- Repository redux-merge-reducers of subcategory Reducer Utilities has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository combineMultiKeyReducers of subcategory Reducer Utilities has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-exr of subcategory Reducer Utilities has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- `<h4>` is not followed by repositories.
- Repository redux-operations of subcategory Advanced Reducer Use Cases has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-list-reducer of subcategory Advanced Reducer Use Cases has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-reducer-factory of subcategory Advanced Reducer Use Cases has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository reducer-generator of subcategory Advanced Reducer Use Cases has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository sliced-redux of subcategory Dynamic Reducer Injection has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-reducers-injector of subcategory Dynamic Reducer Injection has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-async-injector of subcategory Dynamic Reducer Injection has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**side-effects.md**
- Repository redux-thunk of subcategory Widely Used Tools has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository number 1 of subcategory Side Effect Libraries By Approach has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository number 2 of subcategory Side Effect Libraries By Approach has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository number 3 of subcategory Side Effect Libraries By Approach has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository number 4 of subcategory Side Effect Libraries By Approach has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**store-persistence.md**
- Repository redux-offline of subcategory Persistence Libraries has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-persist-migrate-semver of subcategory Redux-Persist Addons has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**store.md**
- Repository redux-live of subcategory Synchronization has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository Redux Share of subcategory Synchronization has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-bolt of subcategory Synchronization has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-dispatch-monitor of subcategory Other has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**testing.md**
- Repository redux-actions-assertions of subcategory Actions has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**use-cases.md**
- `<h3>` appears more than once.
- Repository redux-dag-history of subcategory Undo-Redo has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**utilities.md**
- Repository bo-selecta of subcategory Selectors has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository red-ux of subcategory Selectors has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository redux-fun of subcategory Functional Programming has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**widgets.md**
- Repository react-redux-idle-monitor of subcategory Assorted Components has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository react-block-ui of subcategory Assorted Components has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.
- Repository Repanel of subcategory Layout has wrong structure. It should be : paragraph -> bold title string -> linebreak -> valid github repo url string -> linebreak -> description string.

**Comment by markerikson** [comment]
Hah, wow, that's great!  Would be even niftier if it could report what the current structure is for comparison.

I think it might be helpful if the parser and background logic can handle a couple specific extra cases:

1. There is no Github repo URL at all.  Just show the URL, skip any update/stars stats.  (For filtering purposes, perhaps it could be considered as having 0 stars?)
2. There's a Github repo URL, but also another link or two.  In this case, it would be nice to show the additional links below the main one, either in the list or in a details page for that item.

For example, the `redux-live` entry links to `redux-live`, `redux-live-localdb`, and `redux-live-socketio`, so they're all relevant.

**Comment by dberget** [comment]
> 1. There is no Github repo URL at all. Just show the URL, skip any update/stars stats. (For filtering purposes, perhaps it could be considered as having 0 stars?)

> 2. There's a Github repo URL, but also another link or two. In this case, it would be nice to show the additional links below the main one, either in the list or in a details page for that item.

Along these same lines and I think what you are also saying @markerikson. With a link type on the UI side we can easily render an appropriate variation of the link, or simply apply a "Gist", "Repo", "NPM" tag, etc, which would be nice.

**Comment by wilbertliu** [comment]
Hello @markerikson 👋🏻,

> Hah, wow, that's great! Would be even niftier if it could report what the current structure is for comparison.

Thank you for taking a look. 😀 The purpose of this script is to report which document has errors with the best possible error message that we can make. And the rest should be correcting the document by hands. Isn't seeing the structure of the document is the first step to correct the document by hands?

> There is no Github repo URL at all. Just show the URL, skip any update/stars stats. (For filtering purposes, perhaps it could be considered as having 0 stars?)

I think we don't show URL at all. We show repo name as link and the destination is either GitHub repo URL or anything . But skipping update or any other stats is sure, it's been done. For filter? We've discussed that long time ago to remove that. Check #1 if you want to see the reasons.

> There's a Github repo URL, but also another link or two. In this case, it would be nice to show the additional links below the main one, either in the list or in a details page for that item.

I assume what you mean by _another link or two_ is one or more links that are separated by line-break, and located below the name of repo and above the repo description – it's a good idea! We can put some kind like `See also:  redux-live-localdb, redux-live-socketio.`. cc @dberget 

---

Alright, so back to the document structure discussion. What's your plan after seeing the pattern that I've described above, also the result of some documents that need to be fixed to follow that pattern? Will you rethink about the proper structure for the documents and fix them all? Since how we show the web will be determined by the consistency of the links document that you have. But I & @dberget would love to help when possible.

Let me know your thoughts. 😀🙏🏻

**Comment by dberget** [comment]
Hey @wilbertliu! What is your plan for merging this? I got tied up prepping for a talk but should have more time now to work on #4 , but would like to update to use this instead if possible. 😄

**Comment by wilbertliu** [comment]
Hello @dberget! 👋🏻

Actually I'm waiting for @markerikson response, but it's been a week. 🤔🤷🏻‍♂️
It's important to us in this project because then it's hard to have a good thing when the data that needs to be parsed is not consistent.

But alright then, I'll do what I can.

Recently I've tried to run the robot once again and it seems good, I think we're good to go on this. You could run the robot using this command – `node robot/index.js`.  Just note that `github_star`, `github_last_update`, and `npm_download_since_last_month` are optional.

Let me know if you have any questions.
Will merge this PR and close afterwards.

**Comment by markerikson** [comment]
@wilbertliu : Looking at your last comment, it sounds like you've got this working and merged.  Is there any info or direction you need from me related to this (or anything else for this project) ?

**Comment by wilbertliu** [comment]
@markerikson At first it works, but sometimes doesn't. Not an info, but a clarity on whether or not you want to standardize the markdown structure. As long as those markdowns don't have a proper structure, it's hard to ensure that the robot could work as expected because what it does is scrapping.

**Pull request merged**
